package com.ecommerce.backend.SpringEcommerceAppBackend.entity;

import jakarta.persistence.*; // Importing necessary annotations for JPA
import lombok.Getter; // Importing Lombok annotation for generating getters
import lombok.Setter; // Importing Lombok annotation for generating setters

import java.util.Set; // Importing Set interface from java.util

@Entity // Specifies that this class is an entity mapped to a database table
//@Data // Lombok annotation for generating getters, setters, equals, hashCode, and toString methods
@Table(name = "product_category") // Specifies the name of the database table for this entity
@Getter // Lombok annotation for generating getter methods
@Setter // Lombok annotation for generating setter methods
public class ProductCategory {
    @Id // Specifies that this field is the primary key for the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key value will be automatically generated by the database
    @Column(name = "id") // Specifies the name of the column in the database table
    private Long id; // Unique identifier for the product category

    @Column(name = "category_name") // Specifies the name of the column in the database table
    private String categoryName; // Name of the product category

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "category") // Establishes a one-to-many relationship between ProductCategory and Product entities
    private Set<Product> products; // Set of products associated with this category
}
